<a href="https://colab.research.google.com/github/ashishkumar30/Machine-Learning/blob/master/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import sklearn.metrics as smt
from sklearn.model_selection import train_test_split

In [0]:
from sklearn.datasets import load_digits
dig = load_digits()
dig

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

In [0]:
x = dig.data
y = dig.target

In [0]:
x.shape

(1797, 64)

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
ss = StandardScaler()
ss.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [0]:
scaled_data = ss.transform(x)
scaled_data.shape

(1797, 64)

In [0]:
from sklearn.decomposition import PCA

In [0]:
pca = PCA(n_components=30)
pca.fit(scaled_data)

PCA(copy=True, iterated_power='auto', n_components=30, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [0]:
x_pca = pca.transform(scaled_data)
x_pca.shape

(1797, 30)

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x_pca,y,test_size=0.2,random_state=50)

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
logreg = LogisticRegression()
logreg.fit(x_train,y_train)
y_pred = logreg.predict(x_test)

C:\Users\Genius\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Genius\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [0]:
print("Accuracy score : ",smt.accuracy_score(y_test,y_pred))

Accuracy score :  0.9305555555555556


In [0]:
print("Confusion Matrix:\n",smt.confusion_matrix(y_test,y_pred))

Confusion Matrix:
 [[39  0  0  0  1  0  1  0  0  0]
 [ 0 39  0  0  0  0  0  0  2  1]
 [ 0  0 45  0  0  0  0  0  0  0]
 [ 0  1  0 25  0  1  0  1  0  1]
 [ 0  1  0  0 30  0  0  0  0  0]
 [ 0  0  0  0  0 30  0  0  0  1]
 [ 0  0  0  0  0  0 38  0  0  0]
 [ 0  0  0  0  0  0  0 34  0  1]
 [ 0  3  0  2  1  1  1  0 20  0]
 [ 1  2  0  0  0  0  0  0  2 35]]


In [0]:
print("Classification Report : \n",smt.classification_report(y_test,y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.97      0.95      0.96        41
           1       0.85      0.93      0.89        42
           2       1.00      1.00      1.00        45
           3       0.93      0.86      0.89        29
           4       0.94      0.97      0.95        31
           5       0.94      0.97      0.95        31
           6       0.95      1.00      0.97        38
           7       0.97      0.97      0.97        35
           8       0.83      0.71      0.77        28
           9       0.90      0.88      0.89        40

   micro avg       0.93      0.93      0.93       360
   macro avg       0.93      0.92      0.92       360
weighted avg       0.93      0.93      0.93       360



In [0]:
print("Classification Report : \n",smt.classification_report(y_test,y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.97      0.95      0.96        41
           1       0.85      0.93      0.89        42
           2       1.00      1.00      1.00        45
           3       0.93      0.86      0.89        29
           4       0.94      0.97      0.95        31
           5       0.94      0.97      0.95        31
           6       0.95      1.00      0.97        38
           7       0.97      0.97      0.97        35
           8       0.83      0.71      0.77        28
           9       0.90      0.88      0.89        40

   micro avg       0.93      0.93      0.93       360
   macro avg       0.93      0.92      0.92       360
weighted avg       0.93      0.93      0.93       360

